<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="intex" nsURI="edu.kit.ipd.sdq.intbiis.intex" nsPrefix="intex">
  <eSubpackages name="organizationenvironmentrel" nsURI="http://palladiosimulator.org/PalladioComponentModel/5.1/intex/organizationenvironmentrel"
      nsPrefix="organizationenvironmentrel">
    <eClassifiers xsi:type="ecore:EClass" name="DeviceResourceRel" eSuperTypes="../../de.uhd.ifi.se.pcm.bppcm/model/bp.ecore#//organizationenvironmentmodel/DeviceResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mttf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RoleRel" eSuperTypes="../../de.uhd.ifi.se.pcm.bppcm/model/bp.ecore#//organizationenvironmentmodel/Role">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mttf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mttrep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="bpusagerel" nsURI="http://palladiosimulator.org/PalladioComponentModel/5.1/intex/bpusagerel"
      nsPrefix="bpusagerel">
    <eClassifiers xsi:type="ecore:EClass" name="ActorStepRel" eSuperTypes="../../de.uhd.ifi.se.pcm.bppcm/model/bp.ecore#//bpusagemodel/ActorStep">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReleaseDeviceResourceActionRel" eSuperTypes="../../de.uhd.ifi.se.pcm.bppcm/model/bp.ecore#//bpusagemodel/ReleaseDeviceResourceAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AcquireDeviceResourceActionRel" eSuperTypes="../../de.uhd.ifi.se.pcm.bppcm/model/bp.ecore#//bpusagemodel/AcquireDeviceResourceAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureProbability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
